spring:
  application:
    #指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
    name: consumer
server:
  port: 9000
  servlet:
    context-path: /consumer
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled : true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream